# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f5130ed6543fd76bfe4ca5f8be7cca6e652f4181c73bdb2660f38dc4fd0f7eb0d9e29635bac668bf610e1189147af24e13bd8f44cc88f5f08b4c97b1244256

test:
  secret_key_base: 7c00b240b61c8aa4cfb078118e4c4c43bba41ea167e84ee9a5179177b6466210dba7e4ac87734397e45631c7da659be1abe7f309fe924e8a8dc34c011c5dd81f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
